### ISSUE TITLE
Build error when using  -DWITH_COVERAGE=ON

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#17832]
Build error when using  -DWITH_COVERAGE=ON and with MKLDNN

### All flags used for the build:
```
-DWITH_GPU=OFF -DWITH_MKLDNN=ON -DON_INFER=ON -DWITH_TESTING=ON -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=ON -DWITH_FLUID_ONLY=ON -DWITH_COVERAGE=ON
```
### Error occured:

```
/usr/bin/ar: /repos/paddle_paddle/build/paddle/fluid/inference/libpaddle_fluid_origin.a: File truncated
paddle/fluid/inference/CMakeFiles/paddle_fluid_origin.dir/build.make:6073: recipe for target 'paddle/fluid/inference/libpaddle_fluid_origin.a' failed
```

**Comment by luotao1** [comment]
1. use `-DCMAKE_BUILD_TYPE=Release`
2. use `paddlepaddle/paddle:latest-dev` image
3. fixed by https://github.com/PaddlePaddle/Paddle/pull/15109

**Comment by pmajchrzak** [comment]
flags I used today:
`
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DON_INFER=ON -DWITH_TESTING=ON -DWITH_STYLE_CHECK=ON -DWITH_FLUID_ONLY=ON -WITH_INFERENCE_API_TEST=ON -DWITH_PROFILER=ON -DWITH_COVERAGE=ON
`
mentioned image used…
still doesn't work

**Comment by luotao1** [comment]
Could you try solutions in #15109?

**Comment by ddokupil** [comment]
> Could you try solutions in #15109?

Could you be more specific? We can see that #15109 was merged in Jan but we ran into this issue a couple of days ago. We tried using Release build type and changed our base to paddle:latest-dev (but still rebuild paddle our own way on top of it). Could you point us to dockerfile for that image? Is there anything else we could try?

**Comment by luotao1** [comment]
http://ce.paddlepaddle.org:8080/viewLog.html?buildId=41344&tab=buildLog&buildTypeId=PaddlePaddleFramework_TestCoverage_TestCoverage&logTab=tree&filter=all&_focus=378#_state=308,301,23,30

This log is built on `paddlepaddle/paddle:latest-dev` one months ago.  I see `WITH_PROFILER=OFF`.
Besides, is `paddlepaddle/paddle:latest-dev` on your local machine latest?

**Comment by bingyanghuang** [comment]
@ddokupil @pmajchrzak Have you tried luotao's suggestions? Did you solve your problem. Please follow-up this PR. If your problem has been solved, please help close this PR. Thanks
