### ISSUE TITLE
RuntimeError: (NotFound) No allocator found for the place, Place(undefined:0)

### ISSUE THREAD

**Issue by umayrh** [PaddlePaddle/Paddle#72413]
### bug描述 Describe the Bug

Hi, 

I am confounded by this error with the recent version of Paddle. I'm using Python 3.11.12, PaddlePaddle 3.0.0, PaddleOCR 2.10.0 on Mac OS Sonoma:

```
import paddleocr
text_det = paddleocr.PaddleOCR(
    lang="en", use_gpu=False, use_angle_cls=True, show_log=False)
document_path = 'xyz.jpg'
result = self.text_det.ocr(document_path, cls=False)
```

```
  File "<input>", line 1, in <module>
  File "ocr_service.py", line 47, in read_text
    result = self.text_det.ocr(document_path, cls=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/paddleocr/paddleocr.py", line 766, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls, slice)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/paddleocr/tools/infer/predict_system.py", line 144, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/paddleocr/tools/infer/predict_rec.py", line 793, in __call__
    self.predictor.run()
RuntimeError: (NotFound) No allocator found for the place, Place(undefined:0)
  [Hint: Expected iter != allocators.end(), but received iter == allocators.end().] (at ../paddle/phi/core/memory/allocation/allocator_facade.cc:381)
  [operator < matmul > error]
```

Any ideas?

**Comment by huangjiyi** [comment]
Hi, What chip is in your Macbook? 

I ran the following code on M3 chip and got none errors.

Otherwise, I can reproduce your problem on M2 chip.

``` Python
import paddleocr

text_det = paddleocr.PaddleOCR(
    lang="en", use_gpu=False, use_angle_cls=True, show_log=False)

document_path = './image.png'  # Any image

result = text_det.ocr(document_path, cls=False)
```

**Comment by umayrh** [comment]
> Hi, What chip is in your Macbook?
> 

It's Intel Core i5. I have run the previous version of PaddlePaddle and PaddleOCR on the same machine with no issues, so I'm not sure what has changed recently. I think it works fine on Ubuntu with Intel but will double-check.

**Comment by huangjiyi** [comment]
> I think it works fine on Ubuntu with Intel but will double-check.

I also tested it on Ubuntu with Intel cpu and there is no problem.

**Comment by huangjiyi** [comment]
> I have run the previous version of PaddlePaddle and PaddleOCR on the same machine with no issues

Can you give me the version of PaddlePaddle and PaddleOCR you run with no issues?

**Comment by umayrh** [comment]
> > I have run the previous version of PaddlePaddle and PaddleOCR on the same machine with no issues
> 
> Can you give me the version of PaddlePaddle and PaddleOCR you run with no issues?

I think I didn't see any issues on this Mac with `paddlepaddle==2.6.1` and `paddleocr==2.7.3`

**Comment by puccoonhuang** [comment]
> Hi, What chip is in your Macbook?
> 
> I ran the following code on M3 chip and got none errors.
> 
> Otherwise, I can reproduce your problem on M2 chip.
> 
> import paddleocr
> 
> text_det = paddleocr.PaddleOCR(
>     lang="en", use_gpu=False, use_angle_cls=True, show_log=False)
> 
> document_path = './image.png'  # Any image
> 
> result = text_det.ocr(document_path, cls=False)

How to resolve the issue on M1 chip. I met the same problem.

**Comment by AmirHKiani98** [comment]
I came across the same problem. What resolved it for me was changing the version of my virtual environment to 3.10.4 (I previously had 3.13.3) and installing paddlepaddle using the following command:
```
pip install "https://files.pythonhosted.org/packages/4b/b4/ed559ef9588b5b2c94f52557e14a8966dfcc96918acbb1f6bbbc9f3d7d73/paddlepaddle-3.0.0rc1-cp310-cp310-macosx_11_0_arm64.whl"
```
FYI, I have paddleocr==2.10.0
I guess the only issue happens when using python >= 3.13. According to [link](https://pypi.org/project/paddlepaddle/3.0.0rc1/#files) paddlepaddle==3.0.0rc1 is supported for python >=3.8 and python <=3.12

**Comment by huangjiyi** [comment]
Hi, @umayrh @puccoonhuang 

This issue has been fixed in the latest develop branch, which can be installed using the following command:

``` Bash
python -m pip install --pre paddlepaddle -i https://www.paddlepaddle.org.cn/packages/nightly/cpu/
```

**Comment by puccoonhuang** [comment]
@umayrh @huangjiyi 
Thanks a lot!

**Comment by umayrh** [comment]
> Hi, [@umayrh](https://github.com/umayrh) [@puccoonhuang](https://github.com/puccoonhuang)
> 
> This issue has been fixed in the latest develop branch, which can be installed using the following command:
> 
> python -m pip install --pre paddlepaddle -i https://www.paddlepaddle.org.cn/packages/nightly/cpu/

~I can verify that the issue has been fixed in `paddlepaddle-3.0.0.dev20250424`. Note though that I needed to reinstall `paddleocr` to see the fix take effect.~

Spoke too soon. Still not fixed:

```
import paddleocr
image_path = 'abc.jpg'
text_det = paddleocr.PaddleOCR(lang="en", use_gpu=False, use_angle_cls=True, show_log=False)
result = text_det.ocr(image_path, cls=False)

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
NameError: name 'document_path' is not defined
result = text_det.ocr(image_path, cls=False)
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "venv/lib/python3.11/site-packages/paddleocr/paddleocr.py", line 766, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls, slice)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/paddleocr/tools/infer/predict_system.py", line 144, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/paddleocr/tools/infer/predict_rec.py", line 793, in __call__
    self.predictor.run()
RuntimeError: (NotFound) No allocator found for the place, Place(undefined:0)
  [Hint: Expected iter != allocators.end(), but received iter == allocators.end().] (at /Users/paddle/xly/workspace/a8d1cb05-6b63-445e-8ff4-2bad78994574/Paddle/paddle/phi/core/memory/allocation/allocator_facade.cc:385)
  [operator < matmul > error]
```

**Comment by youms14** [comment]
Hello everyone, the bug is not fixed. I think, it is a limitation is on macOS platform(specially on Mx silicon). The same code on other architectures like Intel Windows is running very well.

**Comment by umayrh** [comment]
> Hello everyone, the bug is not fixed. I think, it is a limitation is on macOS platform(specially on Mx silicon). The same code on other architectures like Intel Windows is running very well.

Hi @youms14 I see this bug on Intel i5 on MacOS so perhaps it is OS-specific (and not arch-specific) and something that the library can address.

**Comment by umayrh** [comment]
Update: I don't see this issue in `paddlepaddle-2.6.2` so it was likely introduced in `paddlepaddle-3.0.0`. I hope y'all can fix this because it severely limits usage. Also, it seems that, at least on my OCR dataset, the inference in `3.0.0` is somewhat worse than before.

**Comment by sdcb** [comment]
also replicated in macos-15 (apple m1 arm64 based), no issue in macos-13(x64 based): https://github.com/sdcb/PaddleSharp/actions/runs/15794011601/job/44523675869

screenshot:
![Image](https://github.com/user-attachments/assets/b7383a56-567a-4528-9ac6-e25ccca8e198)

logs:

```
libc++abi: terminating due to uncaught exception of type common::enforce::EnforceNotMet: 
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
----------------------
Error Message Summary:
----------------------

NotFoundError: No allocator found for the place, Place(undefined:0)
  [Hint: Expected iter != allocators.end(), but received iter == allocators.end().] (at /Users/runner/work/PaddleSharp/PaddleSharp/paddle-src/paddle/phi/core/memory/allocation/allocator_facade.cc:381)
Total tests: Unknown
    Skipped: 1
  [operator < matmul > error]

Test Run Aborted.
 Total time: 2.54[74](https://github.com/sdcb/PaddleSharp/actions/runs/15794011601/job/44523675869#step:8:75) Seconds
     1>Project "/Users/runner/work/PaddleSharp/PaddleSharp/tests/Sdcb.PaddleOCR.Tests/Sdcb.PaddleOCR.Tests.csproj" on node 1 (VSTest target(s)).
     1>_VSTestConsole:
         MSB4181: The "VSTestTask" task returned false but did not log an error.
     1>Done Building Project "/Users/runner/work/PaddleSharp/PaddleSharp/tests/Sdcb.PaddleOCR.Tests/Sdcb.PaddleOCR.Tests.csproj" (VSTest target(s)) -- FAILED.

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.01
Error: Process completed with exit code 1.
```

All other os/arch works:
https://github.com/sdcb/PaddleSharp/actions/runs/15794321676

![Image](https://github.com/user-attachments/assets/89f35819-8e17-491c-b625-b7b56f30da03)
